/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursion_assignment;

import java.awt.Graphics;

/**
 *
 * @author billc
 */
public class HTree extends javax.swing.JPanel {

    /**
     * Creates new form HTree
     */
    public HTree() {
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        tree(g,50,this.getWidth()/2,this.getHeight()/2,3);
    }
    
    /**
     * Recursive method for H tree drawing
     * @param g Graphics 
     * @param size size of the tree
     * @param centerX center x coord of the tree
     * @param centerY center y coord of the tree
     * @param stage stage in recursion
     */
    public static void tree(Graphics g,int size,int centerX,int centerY,int stage){
        //The coordinates of the four vertices of the H
        int x1=centerX-size;
        int y1=centerY-size;
        int x2=x1;
        int y2=centerY+size;
        int x3=centerX+size;
        int y3=y1;
        int x4=x3;
        int y4=y2;
        
        //draws the H from the vertices
        g.drawLine(x1, y1, x2, y2);
        g.drawLine(x1, (y2+y1)/2, x3, (y3+y4)/2);
        g.drawLine(x3, y3, x4, y4);
        
        
        //base case
        if(stage==0){
            return;
        }
        //each of the vertices become their own base for new H
        tree(g,size/2,x1,y1,stage-1);
        tree(g,size/2,x2,y2,stage-1);
        tree(g,size/2,x3,y3,stage-1);
        tree(g,size/2,x4,y4,stage-1);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
